### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_context')

### ISSUE THREAD

**Issue by ziqiangai** [apitable/apitable#444]
After the developer's environment is installed with widget, refresh the interface display the following content：

![image](https://user-images.githubusercontent.com/18455767/220699405-23504515-085b-4729-bfb5-49975e96a9e2.png)

Is there any problem when `EmbedContext` is loaded? Or what kind of built command do I need to execute first.

Because I saw the following code fragment.

https://github.com/apitable/apitable/blob/c95f6daae6eb69a962a3a66359026f963425a859/packages/datasheet/src/pc/components/widget/widget_panel/widget_item/widget_item.tsx#L28-L32

**Comment by Exclamation-mark** [comment]
TypeError: Cannot read properties of undefined (reading '_context')

**Comment by JaneSu** [comment]
This issue has been resolved, please update your code.

**Comment by ziqiangai** [comment]
![image](https://user-images.githubusercontent.com/18455767/220830732-1340f5ab-1120-48b6-ac08-9aa098069945.png)
 
But still can't start the widget.
